In [2]:
import torch

In [15]:
randint = torch.randint(0, 10, (5, 3))
print(randint)

tensor([[2, 2, 9],
        [7, 9, 4],
        [2, 3, 9],
        [7, 5, 2],
        [4, 5, 5]])


In [5]:
tensor = torch.tensor([1, 2, 3])
print(tensor)

tensor([1, 2, 3])


In [6]:
zeros = torch.zeros(5, 3)
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [7]:
ones = torch.ones(5, 3)
print(ones)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [9]:
empty = torch.empty(3, 3)
print(empty)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.1915e-04, 0.0000e+00, 9.6505e-05],
        [0.0000e+00, 3.7988e+00, 1.1210e-43]])


In [11]:
arange = torch.arange(0, 10, step=2)
print(arange)

tensor([0, 2, 4, 6, 8])


In [12]:
linspace = torch.linspace(0, 10, steps=5)
print(linspace)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [13]:
logspace = torch.logspace(0, 10, steps=5)
print(logspace)

tensor([1.0000e+00, 3.1623e+02, 1.0000e+05, 3.1623e+07, 1.0000e+10])


In [16]:
eye = torch.eye(3, 3)
print(eye)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [18]:
t = torch.empty(4, 4, dtype=torch.int64)
empty_like = torch.empty_like(t)
print(empty_like)

tensor([[      131203216,               0,       131057856,       106108224],
        [140152359566416,               0,               0,               0],
        [              0,               0,               0,               1],
        [              0,               0,               0,               0]])
